InsightsHelpers.cpp, tests/ClassOperatorHandler9Test.expect, tests/Issue13.cpp, tests/Issue13.expect, tests/TemplateArgumentsTest.expect
Due to lambdas there is special handling for QualType in case it is a
RecordDecl or a ClassTemplateSpecializationDecl. It appears that, if the
type is a ReferenceType the CV qualifiers come from the reference type
getPointeeTypeAsWritten(). Ohterwise they are empty. This fix adds
special handling for that, nearly the same way as TypePrinter.cpp does
it.
=> Fixed #13: const disappeared in case of auto.

CodeGenerator.cpp, tests/Issue15.cpp, tests/Issue15.expect, tests/TemplateExpansionTest.expect
There is special handling required for user defined literals which are
templated. The libstdc++ under Linux seems to be implemented that way
for seconds. Without this change the parameter list was empty.
=> Fixed #15: user defined literal with template argument.

UserDefinedLiteralHandler.cpp, tests/UserDefinedLiteral2Test.cpp, tests/UserDefinedLiteral2Test.expect
Adjust the UDL matcher to exclude if and switch statements, as they are
handled separately.
=> Fixed user defined literals as subexpression.

ImplicitCastHandler.cpp, StdInitializerListHandler.cpp, tests/InitializerList2Test.cpp, tests/InitializerList2Test.expect
Take more places and cases into account, for example a constructor with
a std::initializer_list and a default argument like std::map.
=> Fixed std::initializer_list.

CodeGenerator.cpp, tests/Issue15.cpp, tests/Issue15.expect, tests/TemplateExpansionTest.expect
With libstc++ the UDL parameter of a cooked literal is passed as char
template arguments to the operator. In the initial fix the comma
separation and the ' where missing.
=> Fixed #15: UDL with libstdc++.

UserDefinedLiteralHandler.cpp, tests/Issue28.cpp, tests/Issue28.expect
The user-defined literal matcher conflicted with the std initializer
list matcher.
=> Fixed #28: Multiple matchers rewrote a statement.

.travis.yml
As a result there is now a "Continuous build" release which gets updated
with each travis-ci build on master. Binaries for macOS and Linux are
provided for convenience.
=> Automatic upload of travis artifacts to github releases.

AutoStmtHandler.cpp, CompilerGeneratedHandler.cpp, FunctionDeclHandler.cpp, tests/AutoHandler7Test.expect, tests/Issue46.cpp, tests/Issue46.expect
Once again the matchers caused trouble. The global autoDecl matcher did
also catch the lambda which resulted in a mess. This fix forwards
autoDecls into CodeGenerator as well and locks it against double match.
=> Fixed issue #46: Lambda's in global scope.

CodeGenerator.cpp, tests/ClassOperatorHandler5Test.expect, tests/LambdaHandler9Test.expect, tests/LoopStatementsTest.expect, tests/SingleLineLoopsTest.cpp, tests/SingleLineLoopsTest.expect
The semicolon at the end of a single unbraced  statement (as body) in a
for- or while-loop was missing which leads to non-compiling code.
=> Fixed missing semi in case of a single statement for/while-loop.

FunctionDeclHandler.cpp, tests/Issue53.cpp, tests/Issue53.expect
Defaulted members outside a class lead to invalid code. The fix ensures,
that such definitions are left alone for now, as there is no code to
generate anyway.
=> Fixed issue #53: Defaulted special members outside a class.

.travis.yml, AutoStmtHandler.cpp, InsightsMatchers.h
This handles cc30333c2cdf3beb6bb32165bf2e5550f9977227 which disabled the
clang current build.
=> Re-enable building with clang current.

CodeGenerator.cpp, CodeGenerator.h, CompilerGeneratedHandler.cpp, TemplateHandler.cpp, tests/CXXMethodTemplateExplicitSpecializationTest.cpp, tests/CXXMethodTemplateExplicitSpecializationTest.expect
A class template which implements a specialized method outside of its
definition needs to have the empty template keyword and name the type for
which it is specialized.
=> Handle specialized class method templates correctly.

CodeGenerator.cpp, tests/Issue60.cpp, tests/Issue60.expect, tests/NonTypeTemplateArgTest.cpp, tests/NonTypeTemplateArgTest.expect, tests/TemplateExpansionTest.expect
In case of non-type template parameters the full type was deduced
instead of the variable itself.
=> Fixed #60: Handle non-type template parameters correctly.

CodeGenerator.cpp, tests/Issue64.cpp, tests/Issue64.expect, tests/LambdaImplicitCaptureTest.cpp, tests/LambdaImplicitCaptureTest.expect
As http://eel.is/c++draft/expr.prim.lambda#capture-10 states, implicit
lambda captures are capture by copy. Insights used the variable type
before which produced an reference for a reference type. This fix strips
the reference in case of an implicit capture and make the resulting
lambda complying  to the standard.
=> Fixed #64: Implicit lambda captures are captured by copy.

CodeGenerator.cpp, tests/ExceptionTest.cpp, tests/ExceptionTest.expect
A catch-all: catch(...) did lead to a crash as it was assumed that
getCaughtType() always returns a valid type. This fix guards it with an
if-clause and re-added the '...' in case of an catch-all.
=> Fixed crash for a catch-all clause.

CodeGenerator.cpp, CodeGeneratorTypes.h, TemplateHandler.cpp, tests/FunctionTemplateDecl2Test.cpp, tests/FunctionTemplateDecl2Test.expect, tests/FunctionTemplateDecl3Test.cpp, tests/FunctionTemplateDecl3Test.expect, tests/FunctionTemplateDeclTest.cpp, tests/FunctionTemplateDeclTest.expect, tests/TypeAliasTemplateTest.cpp, tests/TypeAliasTemplateTest.expect
As most of the time the AST matchers catch a FunctionTemplateDecl this
has gone unseen for a while. If a FunctionTemplateDecl is within a
ClassTemplate the matcher should not trigger, instead it is processed
with the instantiated template.
=> Added support for FunctionTemplateDecl.

CodeGenerator.cpp, tests/UsingNamespaceStdTest.cpp, tests/UsingNamespaceStdTest.expect, tests/testSTDIN.sh
The logic behind this expected that after using always a name follows
which lead to the crash. This fix checks whether there is a name or not.
If not, it continues parsing.
=> Fixed crash for simple code: using namespace std. 

.travis.yml, Insights.cpp, InsightsHelpers.cpp, docker_travis/Dockerfile, tests/Class2Test.expect, tests/Issue50.expect, tests/Issue50_2.cpp, tests/Issue50_2.expect, tests/Issue50_3.expect, tests/StructuredBindingsHandler3Test.ccerr
Use clang 7.0 in Tavis CI and as deployment target such that it is the version used by the web-frontend.
=> Travis clang7

ClangCompat.h, CodeGenerator.cpp, tests/ImplicitValueInitExprTest.cpp, tests/ImplicitValueInitExprTest.expect, tests/LambdaHandlerTest.cpp, tests/LambdaHandlerTest.expect
Before this patch, there was no test to verify that the path
STK_FloatingComplex and STK_IntegralComplex did work as expected. This
patch adds the missing test cases.
=> Added test for complex float and int.

CodeGenerator.cpp, tests/UnresolvedPredefinedExprTest.cpp, tests/UnresolvedPredefinedExprTest.expect
A PredefinedExpr within the definition of a template is unresolved, e.g.
for __func__ the name of the function is unknown in the template itself.
It first appears in an instantiation of a template. Before the fix the
assumption was, that a PredefinedExpr always returns a StringLiteral
with the function name. In the case when the PredefinedExpr was
unresolved that StringLiteral is nullptr. This fix adds a check and
inserts the predefined name in case the name is currently unresolved.
=> Fixed crash in case of a PredefinedExpr which is unresolved.

CodeGenerator.cpp, InsightsHelpers.cpp, tests/Issue102.cpp, tests/Issue102.expect, tests/LambdaAsTemplateArgTest.cpp, tests/LambdaAsTemplateArgTest.expect
Filter only expression to handle them special for TypeAlias and pass the
rest to the normal parser.
=> Fixed #102: Not all TypeAlias's are expressions.

InsightsHelpers.cpp, tests/Issue116.cpp, tests/Issue116.expect
Use the canonical type to get all CVR's.
=> Fixed #116: A typedef concealed the const qualifier.

CodeGenerator.cpp, GlobalVariableHandler.cpp, InsightsStrCat.h, tests/GlobalVarFromFunctionInitTest.cpp, tests/GlobalVarFromFunctionInitTest.expect, tests/Issue131.cpp, tests/Issue131.expect, tests/StructuredBindingsHandler6Test.expect, tests/StructuredBindingsHandler9Test.cpp, tests/StructuredBindingsHandler9Test.expect, tests/TupeInRangeBasedForTest.cerr, tests/TupeInRangeBasedForTest.expect
A global DecompositionDecl which involves a callExpr introduces the
decomposed variables. With this, the global VarDecl matcher matched
multiple times which resulted in an messed up transformation. Added a
limit to the matcher to skip the decomposed variable declarations.
=> Fixed #131: Global DecompositionDecl transformation was wrong.

CodeGenerator.cpp, CodeGenerator.h, Insights.cpp, InsightsHelpers.cpp, tests/StaticHandler4Test.cpp, tests/StaticHandler5Test.cpp, tests/StaticHandler6Test.cpp, tests/StaticHandler6Test.expect, tests/StaticHandlerTest.expect, tests/StaticInLambdaTest.expect, tests/runTest.py
Since C++11 block local statics with a non-trivial constructor or
destructor are thread-safe. Since the beginning the compiler needs to
keep track whether the variable was already initialized. This patch
adds support to show whats is happening in those places.
=> Fixed #119: Show what happens for block local statics.

CodeGenerator.cpp, tests/Issue91.cpp, tests/Issue91.expect, tests/VariadicTemplateRightFoldPlusTest.cpp, tests/VariadicTemplateRightFoldPlusTest.expect
At least in variadic templates with fold expressions the expanded
version does not carry parentheses. For certain operations like `+` and
`-` this leads to wrong results. This fix adds the required parentheses
in the case we have a BinaryOperator and if it is either a `+` or `-`..
See also N4800 [temp.variadic] p10.1 - p10.2.
=> Fixed #91: Add parentheses for BinaryOperator with `+` or `-`.

CodeGenerator.cpp, InsightsOptions.def, tests/Issue44.cpp, tests/Issue44.expect
Subscriptions `E1[E2]` can also be written in the form `*(E1 = E2)`.
This patch adds a command line option (`-alt-syntax-subscription`) 
to select this transformation.
=> Fixed #44: Support alternative representation for a subscription expression.

.travis.yml
The macos build also needs to install gren.
=> Fixed auto generation of release info.

CodeGenerator.cpp, tests/Issue161.cpp, tests/Issue161.expect, tests/RangeForStmtHandlerTest.expect
Some of the recent changes dropped support for single-line range-based
or traditional for-loops. Only `CompoundStmt`s haven been considered.
=> Fixed #161: Show single-line body of for or range-based for loops.

CodeGenerator.cpp, CodeGenerator.h, CodeGeneratorTypes.h, Insights.cpp, InsightsHelpers.cpp
Let VarDecl do the init stuff and only insert the BindingDecls as a
specialty.
=> Simplified DecompositionDecl handling.

CodeGenerator.cpp
A VarDecl which is `static` always has an initializer.
=> Removed dead code.

.gitpod.yml, .gitpod/Dockerfile
Hello! 
Moritz here, I work on Gitpod and I noticed that you configured you build folder to be in `~/home/gitpod/build`. In that location, unfortunately, the contents of that folder will not survive stopping/starting the workspace. 
This PR fixes this by moving the folder to `/workspace/build`. 
Also, this PR changes the workspace-folder in the IDE to be `/workspace` instead of `/workspace/cppinsights`. This way the `build` folder also becomes visible in the IDE's File View.
Also I see that you compile CPP code when the workspace opens. If you wan, this could be done *before* you open a gitpod workspace - just like in CI/CD. If that's something you like, you'd need to configure [the gitpod.io app](https://github.com/apps/gitpod-io) on this repo.
greetings and I hope you find this useful, …
=> [gitpod] Locate build folder in /workspace to survive workspace restarts

CodeGenerator.cpp, CodeGenerator.h, tests/Issue178.cpp, tests/Issue184.cpp, tests/UsingDecl2Test.cerr, tests/UsingDecl2Test.cpp, tests/UsingDecl2Test.expect, tests/UsingDeclTest.expect, tests/VisitorTest.expect
Fixed #178, 184: Provide the functions pulled in from a base class via using.
For example:
```
struct X {
int f(int);
int f(double);
protected:
int x;
};
struct Y: X {
using X::f;
using X::x;
};
```
Will make the functions `f(int)` and `f(double)` available in `Y` as
well as it moves `X::x` from `protected` to `public` in `Y`. All these
functions or members are shown as comments only.
Fixed #184 which points out the invalid prefix from a using decl.
=> Fixed #178, 184: Provide the functions pulled in from a base class via using

CodeGenerator.cpp, tests/TypeAliasTemplate2Test.cpp, tests/TypeAliasTemplate2Test.expect, tests/TypeAliasTemplateTest.expect
The template keyword plus all the template parameters were missing. This
patch adds them as it is done for all other templates.
=> Fixed TypeAliasTemplateDecl.

FunctionDeclHandler.cpp, GlobalVariableHandler.cpp, InsightsHelpers.cpp, InsightsMatchers.h, tests/ClassOperatorHandler4Test.expect, tests/FunctionDeclInMacroLocTest.cpp, tests/FunctionDeclInMacroLocTest.expect, tests/Issue193.cpp, tests/Issue193.expect, tests/NamespaceWithClassOperatorsTest.expect
A global declaration wrapped in a macro was not expanded due to a wrong
starting SourceLocation. This fix considers a starting location which is
inside a macro.
=> Fixed #193: Expand global declaration wrapped in a macro.

CodeGenerator.cpp, InsightsStaticStrings.h, tests/CharLiteralTest.expect, tests/Issue201.cpp, tests/Issue201.expect
The keyword `volatile` was position at the front of a CXXMethodDecl
instead of at the end. This patch corrects the insertion point.
=> Fixed #201: Position the `volatile` keyword at the right side.

OutputFormatHelper.h, TemplateHandler.cpp, tests/CXXScalarValueInitExprTest.expect, tests/Issue199.cpp, tests/Issue199.expect, tests/NonTypeTemplateParameterPackTest.expect, tests/TemplateHandlerTest.expect
If a template parameter was followed by an empty parameter pack an
additional comma was inserted in the template specialization.
=> Fixed #199: An additional `,` was added after a template parameter.

CodeGenerator.cpp, tests/Issue200.expect
With fix for #200 user-provided template specializations where guarded
by an `#if` which does modify the original code. This patch reverts that
behaviour and leaves the rest of the #200 fix as it is.
=> Fixed user-provided template specializations should be without guard.

CodeGenerator.cpp, CodeGenerator.h, tests/Issue205.cpp, tests/Issue205.expect, tests/Issue205_2.cpp, tests/Issue205_2.expect, tests/LambdaAndInClassInitializerTest.cpp, tests/LambdaAndInClassInitializerTest.expect
Lambdas as an in class initializer cause a `LambdaExpr` to occur in a
`CXXConstructorDecl`s initializer list. This causes the lambda to be
placed at a wrong location.
It also triggers a behaviour where the `LambdaExpr` occurs twice. Once
in the in class initializer as written and later in the `CXXConstructorDecl`.
The first one cause a crash due to a `nullptr` access. This patch
filters these lambdas out.
=> Fixed #205: Make lambdas as in class initializer work.

CMakeLists.txt, CodeGenerator.cpp, InsightsHelpers.cpp, InsightsHelpers.h, tests/CharLiteralTest.expect, tests/LambdaAndInClassInitializerTest.expect, tests/runTest.py
Introduced custom TypePrinter to support lambdas `auto` with Clang 9.
In Clang9 the parameter type of a generic lambda remains auto for the
base template. This was introduced with https://reviews.llvm.org/D36527.
While it makes sense for the AST dump, it prohibits generating compiling code.
This patch introduces a own type printer which does handle it properly.
=> Prepare code for Clang 9 changes

InsightsHelpers.cpp, tests/LambdaAsTemplateArgTest.cpp, tests/LambdaAsTemplateArgTest.expect
In case of a `FunctionProtoType` with multiple parameters, wrong code was
generated.
=> Fixed `SimpleTypePrinter`.

CodeGenerator.cpp, tests/CharLiteral2Test.expect, tests/ClassOperatorHandler5Test.expect, tests/ClassOperatorHandler6Test.expect, tests/FunctionalCastTest.expect, tests/ImplicitCast2Test.expect, tests/Issue223.cpp, tests/Issue223_2.cpp, tests/Issue223_2.expect, tests/VarTemplateDecl3Test.expect, tests/VarTemplateWithLambdaTest.expect
Both issues raised that there is a second `static_cast` after a C-style
cast. It turns out, that an `ImplicitCastExpr` has a method
`isPartOfExplicitCast`. This method together which the
`-show-all-implicit-casts` option is used to suppress the second cast
per default.
=> Fixed #223 and #134: Suppress implicit casts which are part of a explicit cast.

CodeGenerator.cpp, tests/Issue238.cerr, tests/Issue238.cpp, tests/Issue238.expect, tests/Issue238_2.cerr, tests/Issue238_2.cpp, tests/Issue238_2.expect, tests/Issue238_3.cerr, tests/Issue238_3.cpp, tests/Issue238_3.expect
In case of a range-based for-loop in something like a template the types
of range statements are not known. In this case just omit them as they
are not there.
=> Fixed #238: Prevent crash of a range-based for-loop in an unevaluated context.

CodeGenerator.cpp, tests/Class2Test.expect, tests/Issue2.expect, tests/Issue205.expect, tests/Issue205_2.expect, tests/Issue233.cpp, tests/Issue233.expect, tests/SpecialMemberTest.expect, tests/VisitorTest.expect, tests/usingConstructorTest.expect
The order in which C++ Insights evaluated whether a special member was
defaulted or deleted was wrong. The deleted check should be before the
defaulted.
=> Fixed #233: Show when the compiler deletes a special member.

CMakeLists.txt, Insights.cpp, RecordDeclHandler.cpp, RecordDeclHandler.h
The old name is no longer correct, as the handler does much more than
just inserting special members. To reflect this it is renamed to a
better matching name.
=> Renamed CompilerGeneratedHandler to RecordDeclHandler.

.travis.yml, appveyor.yml
To have more control about the used LLVM version cache them at GitHub.
This also allows to use a custom build macOS version, as the official
LLVM 9 is still not available.
=> Prepare providing own macOS binary.

tests/Issue176.cpp, tests/Issue176.expect, tests/p0428Test.cpp, tests/p0428Test.expect
The pure switch from LLVM 8 to 9 gives us support for P0428 "templates
lambdas". Hence, only tests are added.
=> Fixed #176: Switching to LLVM 9 gives us P0428.

CMakeLists.txt, Insights.cpp, tests/runTest.py, version.h.in
During adding libc++ support for Linux also addressed a Clang
`resource-dir` issue. This patch adds support to figure out the Clang
resource dir and add it to the command line as first arguments. Those a
user should be able to override them. In general, this hopefully solves
a couple of missing include errors.
=> Added support for using libc++ under Linux.

.travis.yml
Due to broken symbols in Clang 10 disable it temporarily:
```
/usr/lib/llvm-10/lib/libclangTooling.a: error adding symbols: File format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Additionally, fixed Travis-CI macOS build tampering with the date to allow the macOS installer to install `macOS_SDK_headers_for_macOS_10.14.pkg` which unfortunately is not pre-installed on Travis-CI. It worked without the date hack before, but the signature of the package seems to be invalid since a few days.
=> Temporarily disable Clang 10 (unstable) builds and trick macOS build

CodeGenerator.cpp, InsightsHelpers.cpp, tests/CXXFoldExprTest.expect, tests/ClassOperatorHandler5Test.expect, tests/ClassOperatorHandler9Test.expect, tests/ConstexprFunctionHandlerTest.expect, tests/FoldExpressionTest.cpp, tests/FoldExpressionTest.expect, tests/FunctionalCast2Test.expect, tests/Issue264.cpp, tests/Issue264.expect, tests/Issue91.expect, tests/LambdaAsTemplateArgTest.expect, tests/LambdaHandler5Test.expect, tests/LambdaHandler6Test.expect, tests/LambdaHandlerTest.expect, tests/StructuredBindingsHandler3Test.expect, tests/TemporaryHandler2Test.expect, tests/VarTemplateDecl3Test.expect, tests/VariadicTemplateRightFoldPlusTest.expect
This goes not only for `BinaryOperators`in fold expressions. All
expressions with a `BinaryOperator` are now wrapped.
While processing #264 there was another error with the `TypePrinter`
regarding the lambdas `auto` parameter which is fixed by this patch
as well.
=> Fixed #264: Wrap BinaryOperators in their according parentheses.

CodeGenerator.cpp, tests/CXXFoldExprTest.expect, tests/Issue184.expect, tests/Issue254.cpp, tests/Issue254.expect, tests/LambdaInMemberCallExprTest.cerr, tests/LambdaInMemberCallExprTest.expect, tests/MemberExprTemplateTest.expect, tests/NonTypeTemplateParameterPackTest.expect, tests/TemplateMemberFunctionTest.cerr, tests/TemplateMemberFunctionTest.expect, tests/TupeInRangeBasedForTest.expect
Due to another issue (#255) the result of this issue does not compile.
This will be fixed with #255.
=> Fixed #254: Show `MemberExpr` template parameters as comment.

CodeGenerator.cpp, CodeGenerator.h, InsightsHelpers.cpp, InsightsOnce.h, tests/DeductionGuideTest.cerr, tests/DeductionGuideTest.cpp, tests/DeductionGuideTest.expect, tests/Issue101.expect, tests/Issue102.expect, tests/Issue15.expect, tests/TemplateArgumentsTest.expect, tests/TemplateMemberFunctionTest.expect, tests/TemplatesWithAutoAndLambdaTest.expect
Simplified `InsertTemplateArgs` by making it a template.
Aligned template output of type `char`.
Removed duplicate code in `GetValueOfValueInit` and `InitListExpr`.
Added function to get class or struct tag name.
=> Simplified `InsertTemplateArgs` by making it a template and other things.

CodeGenerator.cpp, InsightsHelpers.cpp, tests/autoRefAndConst2Test.cpp, tests/autoRefAndConst2Test.expect, tests/autoRefAndConstTest.cpp, tests/autoRefAndConstTest.expect
In the following example:
```C++
static std::vector<int> gV;
const std::vector<int>& get() {
return gV;
}
auto& aV = get();
```
the resulting type of `aV` should be `const std::vector<>` and not just
`std::vector`.
=> Fixed a missing `const` for `auto&` deduction.

CodeGenerator.cpp, CodeGenerator.h, Insights.cpp, Insights.h, InsightsOptions.def, docs/CommandLineOptions.md, docs/OptionDocumentationGenerator.cpp, docs/cmdl-examples/edu-show-initlist.cpp, tests/StdInitializerList2Test.cerr, tests/StdInitializerList2Test.cpp, tests/StdInitializerList2Test.expect, tests/StdInitializerList3Test.cerr, tests/StdInitializerList3Test.cpp, tests/StdInitializerList3Test.expect, tests/StdInitializerList4Test.cerr, tests/StdInitializerList4Test.cpp, tests/StdInitializerList4Test.expect, tests/StdInitializerListTest.cerr, tests/StdInitializerListTest.cpp, tests/StdInitializerListTest.expect
This is somewhat of an educational transformation as the resulting code
will not compile. The compiler always does this expansion when passing a
std::initializer_list.
Please note also, that it is the way libc++ does implement the type.
=> Added support for transformation of a std::initializer_list.

CodeGenerator.cpp, CodeGenerator.h, tests/StdInitializerList5Test.cpp, tests/StdInitializerList5Test.expect
expansion.
The following code:
```C++
int f(std::initializer_list<int> l);
int main()
{
return f({1, 2, 3});
}
```
did put the initializer list after the return and not before it.
=> Fixed std::initializer_list expansion bug when a return is before the

InsightsHelpers.cpp, tests/AutoHandlerTest.expect, tests/Issue255.expect, tests/Issue286.cpp, tests/Issue286.expect, tests/Issue286_2.cpp, tests/Issue286_2.expect, tests/StructuredBindingsHandler3Test.expect
This case was missed before and should be expanded as well. A few other
places turned up which profit from that change.
=> Fixed #286: Desugar decltype(x) even when it is an LValueReference.

CodeGenerator.cpp, InsightsMatchers.h, tests/Issue292.cpp, tests/Issue292.expect, tests/NullToMemberPointerTest.cpp, tests/NullToMemberPointerTest.expect
Some implicit conversions have been hidden from the start. As this issue
lays out, this is suboptimal for some of them. This change enabled more
conversion that turn up if `--show-all-implicit-casts` is enabled.
=> Fixed #292: Show more hidden conversions to improve overload resolution information.

TemplateHandler.cpp, tests/Issue298.cpp, tests/Issue298.expect
Getting the correct end location of a function template seems to be
challenging. In case of #298 it is followed by an additional semi which
results in an `EmptyDecl`. This fix takes a possible `EmptyDecl` into
account and tries to find the end depending whether a semi is required.
Which is for example in case of CTAD.
=> Fixed #298: Handle additional semi at the end of a function template.

CodeGenerator.cpp
This bug was fixed in Clang 9, see https://bugs.llvm.org/show_bug.cgi?id=33236.
=> Cleaned up a former Clang bug under Windows #33236.

.travis.yml, CMakeLists.txt, CodeGenerator.cpp, Insights.cpp, InsightsHelpers.cpp, InsightsHelpers.h, InsightsMatchers.h, InsightsStrCat.h, OutputFormatHelper.cpp, tests/StaticHandler4Test.expect, tests/StaticHandler5Test.expect, tests/StaticHandler6Test.expect, tests/StaticHandlerTest.expect, tests/StaticInLambdaTest.expect, tests/TypeIdInTemplateTest.cpp, tests/TypeIdInTemplateTest.expect, tests/autoRefAndConstTest.expect, tests/runTest.py
Added support for `runTest.py` under Windows.
To achieve this, the binary name in `CMakeLists.txt` is now platform
independent. In addition `cmake` is used to find the name of the `python3`
binary. The Windows binary is now located directly in the build folder
and now longer under `Release` or `Debug`.
To be as independent as possible, differences in test results are shown
via Python `difflib` instead of the former Unix `diff`.
=> Run test on Windows

CodeGenerator.cpp
This bug manifested under Windows other OSs seem to be fine.
=> Fixed life-time bug of a `std::string` append.

CodeGenerator.cpp, tests/Issue223_2.expect, tests/Issue313.cpp, tests/Issue313.expect, tests/Issue313_2.cpp, tests/Issue313_2.expect
`CK_NoOp` stands for adding `const` or other qualifiers. Show this
conversion, if `--show-all-implicit-casts` is active.
This patch enables showing implicit casts for member-function calls
as well.
=> Fixed #313: Show `CK_NoOp` correctly.

CodeGenerator.cpp, CodeGenerator.h, CodeGeneratorTypes.h, FunctionDeclHandler.cpp, OutputFormatHelper.cpp, tests/AlignAsTest.cpp, tests/AlignAsTest.expect, tests/AttributesTest.cpp, tests/AttributesTest.expect, tests/AutoHandlerTest.expect, tests/Issue311.cpp, tests/Issue311.expect, tests/p1143Test.cpp, tests/p1143Test.expect
Before this patch C++ Insights did not support attributes. The missing
`alignas` specifier that is the reason for #311 is modeled as an
attribute. Hence, this patch also brings support for all other C++
attributes.
Along these lines, P1143 `constinit` which is also modeled as an attribute, is
supported as well.
=> Fixed #311: Added support for attributes in general.

CodeGenerator.cpp, CodeGenerator.h, tests/DependentScopeDeclRefExprTest.cpp, tests/DependentScopeDeclRefExprTest.expect
It was not treading the `template` keyword correctly.
=> Fixed `DependentScopeDeclRefExpr`.

CodeGenerator.cpp, GlobalVariableHandler.cpp, InsightsHelpers.cpp, InsightsHelpers.h, RecordDeclHandler.cpp, tests/AnonymousStructInMacro2Test.cpp, tests/AnonymousStructInMacro2Test.expect, tests/AnonymousStructInMacro3Test.cpp, tests/AnonymousStructInMacro3Test.expect, tests/AnonymousStructInMacroTest.cpp, tests/AnonymousStructInMacroTest.expect, tests/AnonymousStructTest.cpp, tests/AnonymousStructTest.expect, tests/Issue290.cpp, tests/Issue290.expect
To this point unions where shown as a struct, as Clang internally models
them as a CXXRecordDecl.
Also unsupported where anonymous structs. Due to the declaration order
in Clang a name based on line/column prefixed with `__anon_` is made up
to be able to refer to the struct later in a `FieldDecl`.
=> Fixed #290: Added support for unions and anonymous structs.

CodeGenerator.cpp, tests/Issue324.cpp, tests/Issue324.expect
If we have a tenary-operator used within a `MaterializeTemporaryExpr`
the expression needs to be wrapped in parenthesis to make it correct.
=> Fixed #325: Added missing parenthesis.

InsightsHelpers.cpp, tests/ClassOperatorHandler7Test.expect, tests/Issue101.expect, tests/Issue323.cpp, tests/Issue323.expect, tests/Issue60.expect, tests/Issue92.expect, tests/TemplateKeywordTest.expect, tests/TemplateSpecializationWithDependentTypeTest.expect
For other instantiations this change removes namespaces. However, all of
them seem redundant. With this patch they look cleaner and correct.
=> Fixed #323: Missing final specialization is now there.

FunctionDeclHandler.cpp, tests/Issue333.cpp, tests/Issue333.expect
Functions like `operator new` and `operator delete` carry a hidden
attribute `__attribute__((visibility("default")))` which has no valid
`SourceLocation` as it is inherited from the STL. This patch adds code
to use only a valid `SourceLocation` to apply the offset to it to get
the replacement range of the `FunctionDecl`.
=> Fixed #333: Check for valid `SourceLocation` of attributes.

CMakeLists.txt, Readme.md
Fixed Issue #186: 
- Added a flag to `CMakeLists.txt` to not elevate the includes to system includes (i.e. skipping the regex replacement from `-I` to `-isystem`). 
That resolved the issue described in issue #186 but it uncovered another issue:
```
% cmake -G"Ninja" ../cppinsights
cmake -G"Ninja" ../cppinsights
-- llvm_config(LLVM_CXXFLAGS)=>-I/usr/include    -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS;
-- llvm_config(LLVM_LDFLAGS)=>-L/usr/lib;
-- llvm_config(LLVM_LIBS2)=>-lLLVM-10;
-- llvm_config(LLVM_LIBDIR)=>/usr/lib;
-- llvm_config(LLVM_INCLUDE_DIR)=>/usr/include;
-- llvm_config(LLVM_SYSTEM_LIBS2)=>;
-- llvm_config(LLVM_PACKAGE_VERSION)=>10.0.1;
-- llvm_config(LLVM_INCLUDE_DIR)=>/usr/include;
-- Generating version.h
-- Found …
```
=> Fixed Issue #186: Build fails on Arch Linux

CodeGenerator.cpp, InsightsStaticStrings.h, tests/Issue279.expect, tests/Issue349.cpp, tests/Issue349.expect, tests/NullToMemberPointerTest.expect
This patch distinguished between a function-pointer and a
member-variable-pointer. A function-pointer is still prefixed with
`FuncPtr`.
=> Fixed #349: Name pointer to member variable `MemberVarPtr`.

InsightsHelpers.cpp
fix err: could not convert ‘str.llvm::SmallString<16>::str()’ from ‘llvm::StringRef’ to ‘const string’
=> EvaluateAsFloat() fix return value

TemplateHandler.cpp, tests/Issue365.cpp, tests/Issue365.expect
As `CXXDeductionGuideDecl` are made by the compiler their line/column
information can tell that it appears right in the middle of a primary
template. This fix adds a check whether to trust and use the information
from `CXXDeductionGuideDecl` or the one from the deduced template.
=> Fixed #365: `CXXDeductionGuideDecl` appeared in the middle of a template

FunctionDeclHandler.cpp, tests/Issue354.cpp, tests/Issue354.expect
The current implementation assumed that attributes always
come before the return-type. However, this is not the case.
This patch uses the attribute location only if it is before
the location of the function declaration.
=> Fixed #354: Attribute which appeared after return type was broken.

CodeGenerator.cpp, tests/Issue369.cpp, tests/Issue369.expect, tests/Issue369_1.cpp, tests/Issue369_1.expect, tests/Issue369_2.cpp, tests/Issue369_2.expect
This patch does take `CallExpr` into account which can initialize a
`static`variable as well. In such a case the implementation did not
consider providing a constructor to `new`. This patch add the missing
functionality.
=> Fixed #369: When generating block-scope static consider functions as initializer

CodeGenerator.cpp, tests/Issue131.expect, tests/Issue20.expect, tests/Issue277.cpp, tests/Issue277.expect, tests/Issue277_2.cpp, tests/Issue277_2.expect, tests/Issue381.expect, tests/StructuredBindingsHandler3Test.expect, tests/StructuredBindingsHandler5Test.expect, tests/StructuredBindingsHandler6Test.expect, tests/StructuredBindingsHandler9Test.expect, tests/TupeInRangeBasedForTest.expect
In structured bindings, when we have a tuple-like type, show the
underlaying type behind `std::tuple_element<>::type`. Most of the time
this is what is the most interesting.
=> Fixed #277: Consistently show the underlaying type of a binding.

CodeGenerator.cpp, InsightsHelpers.cpp, tests/Final2Test.cpp, tests/Final2Test.expect, tests/Issue374.expect, tests/Issue391.cpp, tests/Issue391.expect, tests/MemberPointerTest.cpp, tests/MemberPointerTest.expect, tests/conceptsConstraintsTest.cpp, tests/conceptsConstraintsTest.expect
Aside from fixing the position of `final` in a class template this patch
corrects the transformation of a member-pointer, which was also invalid.
=> Fixed #391: Placement of `final` was wrong for a class template.

CodeGenerator.cpp, CodeGenerator.h, tests/ClassOpInTemplateFunctionTest.expect, tests/Issue199.expect, tests/Issue200.expect, tests/Issue400.cpp, tests/Issue400.expect, tests/NonTypeTemplateParameterPackTest.expect, tests/StructuredBindingsHandler5Test.expect, tests/StructuredBindingsHandler6Test.expect, tests/TemplateArgumentsTest.expect
=> Fixed #400: Show value of a `ConstantExpr` instead of the subexpr in

CodeGenerator.cpp, tests/Issue408.cpp, tests/Issue408.expect, tests/StaticDataMemberKeepScopeTest.cpp, tests/StaticDataMemberKeepScopeTest.expect
Previously the scope of a variable was lost if it was a static data
member with an initialization outside of the class, or a variable
declared in a namespace and initialized outside the namespace.
=> Fixed #408: Keep scope of variable.

ClangCompat.h, CodeGenerator.cpp, FunctionDeclHandler.cpp, Insights.cpp, InsightsHelpers.cpp, InsightsMatchers.h, TemplateHandler.cpp
Removed code that is used by Clang < 10 which is no longer supported by
this project.
=> Pre Clang 10 cleanup.

CodeGenerator.cpp, CodeGenerator.h, InsightsUtility.h, tests/IfSwitchInitHandlerTest.cpp, tests/IfSwitchInitHandlerTest.expect
In the case where the initialization of an `if` or `switch` was only a
call, the newline was missing.
=> Fixed `if` or `switch` with initialization.

InsightsHelpers.cpp, tests/Issue404.cerr, tests/Issue404.cpp, tests/Issue404.expect
While this fix addresses the original issue, the construction of an
array as shown is invalid. This could be something resolved by #406.
=> Fixed #404: Unintentional swapping of array dimensions.

CodeGenerator.cpp, CodeGenerator.h, tests/usingConstructorTest.expect
The access specifier for inherited constructors was duplicated. The
remove of this duplication lead to the drop of an now unused parameter
for `InsertAccessModifierAndNameWithReturnType`.
=> Fixed inherited constructor's access specifier.

CodeGenerator.cpp, OutputFormatHelper.cpp, OutputFormatHelper.h, tests/usingConstructor2Test.cpp, tests/usingConstructor2Test.expect
In case a user did not name the parameter in a base classes constructor
the resulting transformation in C++ Insights looked like a call to the
default constructor. This patch creates a parameter name in that case.
=> Fixed a special case of inherited constructors.

CodeGenerator.cpp, tests/Issue131.expect, tests/Issue20.expect, tests/Issue381.expect, tests/Issue425.cpp, tests/Issue425.expect, tests/StructuredBindingsHandler10Test.cpp, tests/StructuredBindingsHandler10Test.expect, tests/StructuredBindingsHandler3Test.expect, tests/StructuredBindingsHandler5Test.expect, tests/StructuredBindingsHandler6Test.expect, tests/StructuredBindingsHandler8Test.cpp, tests/StructuredBindingsHandler8Test.expect, tests/StructuredBindingsHandler9Test.expect, tests/TupeInRangeBasedForTest.expect, tests/dcl.struct.bind.Test.cpp, tests/dcl.struct.bind.Test.expect
This patch changes the behavior of how the resulting reference type of a
binding is determined. Now, the code uses the holding variables
type information of a `BindingDecl`. This seems to be consistent with
what Clang does.
The reference kind of a binding is determined by the declaration of the
structured binding.
In [dcl.struct.bind] the standard says that the reference type for a
binding is an lvalue reference if the initializer is an lvalue and
otherwise a rvalue reference. The initializer here donates to the hidden
object, referenced as e. WE declare this implicitly by declaring the
structured binding.
We get an rvalue reference in case we declare the structured binding as
a non-reference like this:
```
auto [a, b, c]
```
We get an lvalue reference if the structured binding is …
=> Fixed #425: Show the correct reference type for structured bindings.

CodeGenerator.cpp, InsightsOptions.def, InsightsStrCat.h, docs/CommandLineOptions.md, docs/cmdl-examples/edu-show-padding.cpp, docs/opt-edu-show-padding.md, tests/PaddingTest.cpp, tests/PaddingTest.expect
This transformation is inspired by Vittorio Romeo (https://twitter.com/supahvee1234/status/1455965666385833984).
The transformation shows the padding bytes introduced by the compiler.
It obeys alignment changes like from `alignas` or pragma aligns.
=> Added a new educational transformation to show padding bytes.

CodeGenerator.cpp, CodeGenerator.h, tests/Issue454.cpp, tests/Issue454.expect
The first implementation left member functions untransformed. This patch
adds support for them.
=> Fixed #454: Added missing support for noexcept transformation.

InsightsHelpers.cpp
Fixed #509: `inline namespace` in global scope
In function `GetScope` at `InsightsHelpers.cpp:455`, when the argument `declCtx` is a `inline namespace` in global scope, it becomes the global scope after running the while loop and `declCtx->getParent()` returns an empty pointer, which causes segmentation fault.
=> Fixed #509: `inline namespace` in global scope

CoroutinesCodeGenerator.cpp, tests/EduCoroutineAllocFailureTest.expect, tests/EduCoroutineBinaryExprTest.cerr, tests/EduCoroutineBinaryExprTest.expect, tests/EduCoroutineCaptureConstTest.cerr, tests/EduCoroutineCaptureConstTest.expect, tests/EduCoroutineCoAwaitOperatorTest.expect, tests/EduCoroutineCoreturnWithCoawaitTest.cerr, tests/EduCoroutineCoreturnWithCoawaitTest.expect, tests/EduCoroutineCustomYieldTypeTest.cerr, tests/EduCoroutineCustomYieldTypeTest.expect, tests/EduCoroutineSimpleTest.cerr, tests/EduCoroutineSimpleTest.expect, tests/EduCoroutineSuspendNeverBoolTest.expect, tests/EduCoroutineSuspendNeverTest.expect, tests/EduCoroutineTemplateGeneratorTest.expect, tests/EduCoroutineVoidTest.expect, tests/EduCoroutineWithDtorTest.expect, tests/EduCoroutineWithExceptionHandlerTest.expect, tests/EduCoroutineWithLambdaTest.expect, tests/Issue536.cerr, tests/Issue536.expect, tests/Issue536_2.expect
Removed calls to `__builtin_coro_nnn` because they lead to crashes when executing the transformed code.
=> Improved coroutine support.

CodeGenerator.cpp, CodeGenerator.h, CoroutinesCodeGenerator.cpp, InsightsHelpers.cpp, tests/EduCoroutineBinaryExprTest.cpp, tests/EduCoroutineBinaryExprTest.expect, tests/EduCoroutineCaptureConstTest.cerr, tests/EduCoroutineCaptureConstTest.expect, tests/EduCoroutineCaptureThisTest.cpp, tests/EduCoroutineCaptureThisTest.expect, tests/EduCoroutineCoAwaitOperatorTest.cerr, tests/EduCoroutineCoAwaitOperatorTest.expect, tests/EduCoroutineCoreturnWithCoawaitTest.cerr, tests/EduCoroutineCoreturnWithCoawaitTest.expect, tests/EduCoroutineCustomYieldTypeTest.expect, tests/EduCoroutineExprTest.cpp, tests/EduCoroutineExprTest.expect, tests/EduCoroutineVoidTest.expect, tests/Issue518.cpp, tests/Issue518.expect
The original issue uncovered more shortcomings in the coroutine transformation.
a) It appears that `operator co_await` is the _only_ operator so far
which must have a space between "operator" and the operator name.
b) Since `co_await` is an expression the keyword can occur in a lot of
places, like lambdas. One limitation over lambdas is that a
`co_await` occurs only in a `CoroutineBodyStmt`.
This patch adds support for more case, however, some are of these
transformations lead to code that is not logically correct. For
example, all loop related statements with a `co_await` as a condition
or increment expression are logically incorrect and I don't know a
way to make them correct.
=> Fixed #518: Support for `co_await` in a `VarDecl` and more.

CodeGenerator.cpp, InsightsOptions.def, docs/cmdl-examples/show-all-callexpr-template-parameters.cpp, docs/opt-show-all-callexpr-template-parameters.md, tests/Issue501.cpp, tests/Issue501.expect
While there are times when seeing the template parameters for a function call is beneficial, it can also clutter the output in cases where you look for something different. Hence, I made this an option.
=> Fixed #501: Added a dedicated option to show all `CallExpr` template parameters.

CodeGenerator.cpp, CodeGeneratorTypes.h, tests/Issue598.cpp, tests/Issue598.expect
Basic means that the expression is not evaluated. C++ Insights only echos the builtin name that was used.
=> Fixed #598: Added basic support for `SourceLocExpr`.

Readme.md
Casting from `Derived` to `Base` is an upcast and not a downcast.
=> Resolve mistake in README

docs/Doxyfile.in
Headers are in the repository root, so strip that when generating Doygen documentation.
=> Strip include path in Doxygen docs

CodeGenerator.cpp, tests/Issue628.cerr, tests/Issue628.cpp, tests/Issue628.expect, tests/runTest.py
This patch fixes a crash. Certain parts of the coroutine transformation aren't correctly transformed to C code due to the architecture of the CodeGenerators.
=> Fixed #628: Cfront mode and coroutines.

ASTHelpers.cpp, ASTHelpers.h, CfrontCodeGenerator.cpp, CodeGenerator.cpp, CodeGenerator.h, CoroutinesCodeGenerator.cpp, Insights.cpp, Insights.h, InsightsHelpers.cpp, docs/cmdl-examples/edu-show-cfront.cpp, tests/EduCfrontTest5.expect, tests/EduCfrontTest7.expect, tests/EduCfrontTest8.expect, tests/EduCfrontVtable2Test.cpp, tests/EduCfrontVtable2Test.expect, tests/EduCfrontVtable3Test.cpp, tests/EduCfrontVtable3Test.expect, tests/EduCfrontVtable4Test.cpp, tests/EduCfrontVtable4Test.expect, tests/EduCfrontVtable5Test.cpp, tests/EduCfrontVtable5Test.expect, tests/EduCfrontVtable6Test.cpp, tests/EduCfrontVtable6Test.expect, tests/EduCfrontVtablePureFuncTest.cpp, tests/EduCfrontVtablePureFuncTest.expect, tests/EduCfrontVtableTest.cpp, tests/EduCfrontVtableTest.expect
Unsupported for now is virtual inheritance as well as how a `dynamic_cast` translates.
=> Added support for vtable visualization in Cfront mode.

CMakeLists.txt
debug needs -g and disble -Werror
warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
=> Fix cmake -DDEBUG

CodeGenerator.cpp, tests/Issue681.cpp, tests/Issue681.expect
If the code contains compiler builtin functions, it will crash with `/usr/include/c++/14.2.1/string_view:297: constexpr void std::basic_string_view<_CharT, _Traits>::remove_prefix(size_type) [with _CharT = char; _Traits = std::char_traits<char>; size_type = long unsigned int]: Assertion 'this->_M_len >= __n' failed.`
In other words: "support compiler builtin functions"
eg:
```cpp
#include <inttypes.h>
/* WARNING: undefined if a = 0 */
static inline int clz32(unsigned int a)
{
return __builtin_clz(a);
}
/* WARNING: undefined if a = 0 */
static inline int clz64(uint64_t a)
{
return __builtin_clzll(a);
}
/* WARNING: undefined if a = 0 */
static inline int ctz32(unsigned int a)
{
return __builtin_ctz(a);
}
/* WARNING: undefined if a = 0 */
static inline int ctz64(uint64_t a)
{
return …
```
=> Fix potential out-of-bounds access by checking if  `start` is empty before removing prefix

.github/workflows/ci.yml, scripts/llvm-coverage.py, scripts/prepare-release.py
The idea is to
1) run the `prepare-release.py` script locally to switch to a new Clang version. 
2) workflow runs and uploads assets to continuous
3) use the tag `prepare-release` created, update it if necessary,  and push it to the remote.
=> Support for automatically building a GitHub release.
