- CodeGenerator.cpp
- tests/Issue20.expect
- tests/StructuredBindingsHandler2Test.cpp
- tests/StructuredBindingsHandler2Test.expect
- tests/StructuredBindingsHandler3Test.cpp
- tests/StructuredBindingsHandler3Test.expect
- tests/StructuredBindingsHandler6Test.expect
- tests/TemplateExpansionTest.expect
- tests/TupeInRangeBasedForTest.cerr
- tests/TupeInRangeBasedForTest.expect
Structured bindings were partially wrong. In general bindings are
references to the members or array elements.
> Improved structured bindings.

- .travis.yml
- scripts/travis_install.sh
Add caching capability with ccache and for brew packages. Reduce the
noise of console output and skip brew auto update.
> Enable travis-ci caching.

- Readme.md
- scripts/getinclude.py
Added examples about how to use C++ Insights from the command-line.
> Fixed #34: Improve documentation.

- CodeGenerator.cpp
- OutputFormatHelper.cpp
- OutputFormatHelper.h
Refactoring left some now unused functionality behind. Remove it to stay clean.
> Remove unused code.

- CMakeLists.txt
Added the install target so the build can be installed with 
cmake --build . --target install
> Creates install target

- scripts/getinclude.py
The include paths are normalized. The script now supports both Python 2
and Python 3.
> Supporting Python 3 and normalizing paths

- .travis.yml
- scripts/travis-clang-format-check.sh
- Added a clang-format check build to Travis CI.
- Updated uploadtool to a new version.
- Added sha256 generation for the gz files and upload them to GitHub as well.
> Travis clang format check

- .github/grenrc.json
- .travis.yml
Using github-release-notes to automatically generate release notes for
continuous.
> Started using github-release-notes.

- CMakeLists.txt
- CodeGenerator.cpp
- CodeGeneratorTypes.h
- InsightsHelpers.cpp
- tests/RangeForStmtHandler6Test.expect
> Removed Clang 7 compatibility code and enabled C++2a test.

- .travis.yml
- appveyor.yml
Added trigger to rebuild  [cppinsights-container](https://github.com/andreasfertig/cppinsights-container) after C++ Insights build.
> Added trigger to rebuild Docker cppinsights-container

- CodeGenerator.cpp
- InsightsHelpers.cpp
- InsightsHelpers.h
- tests/Issue101.cpp
- tests/Issue101.expect
- tests/TemplateKeywordTest.cerr
- tests/TemplateKeywordTest.cpp
- tests/TemplateKeywordTest.expect
Removed duplicated <...> insertion. In addition, insert the template
keyword and suppress the namespace.
> Fixed #101: Support correct transformation of the template parts.

- CodeGenerator.cpp
- CodeGeneratorTypes.h
- FunctionDeclHandler.cpp
- docs/Contents.md
- docs/Coroutines.md
- tests/CoroutinesCoReturnPlusTest.cpp
- tests/CoroutinesCoReturnPlusTest.expect
- tests/ExternCTest.expect
- tests/Issue92.cpp
- tests/Issue92.expect
For more information see docs.cppinsights.io/transformations-coroutines.html.
> Fixed #92: Added support to show coroutines as written.

- CodeGenerator.cpp
- CodeGenerator.h
- CodeGeneratorTypes.h
- InsightsHelpers.cpp
- InsightsHelpers.h
- InsightsStaticStrings.h
- OutputFormatHelper.h
- tests/concepts2Test.cpp
- tests/concepts2Test.expect
- tests/conceptsConstraintAutoVariable.cpp
- tests/conceptsConstraintAutoVariable.expect
- tests/conceptsConstraintsTest.cpp
- tests/conceptsConstraintsTest.expect
- tests/conceptsDefinition.cpp
- tests/conceptsDefinition.expect
- tests/conceptsRequiresRequiresTest.cpp
- tests/conceptsRequiresRequiresTest.expect
- tests/conceptsTest.cpp
- tests/conceptsTest.expect
In most places this does nothing more than re-generating the correct
keywords. In case, of template instantiations the requirements are
treated as fulfilled and left out.
> Added support for C++20 Concepts.

- CodeGenerator.cpp
- CodeGeneratorTypes.h
- tests/Shafik1.cpp
- tests/Shafik1.expect
Ok you did ask: https://twitter.com/shafikyaghmour/status/1370048056729604103?s=20
This seems to be a GNU statement expression extension.
> Fixed cursed code by Shafik Yaghmour. Don't ask.

- .github/workflows/ci.yml
- InsightsHelpers.cpp
Fix #458: Compile with Clang 14.
> Clang14 compile

- CMakeLists.txt
- ClangCompat.h
- CodeGenerator.cpp
- CoroutinesCodeGenerator.cpp
Linking against a new lib (libClangSupport) is required.
> Clang-15 support

- Readme.md
> Update README.md, add vim plugin

- CodeGenerator.cpp
- tests/RangeForStmtHandlerCpp14Test.cpp
- tests/RangeForStmtHandlerCpp14Test.expect
- tests/RangeForStmtHandlerCpp17Test.cpp
- tests/RangeForStmtHandlerCpp17Test.expect
The two function begin and end can differ in C++17 not C++14.
> Fixed range-based for-loop transformation begin and end.

- Readme.md
This pull request corrects the "Get Involved" anchor link in the README file to ensure it correctly navigates to the intended section. 
- Updated the "Get Involved" anchor link from `getinvolved` to `get-involved` to point to correct section.
> fix: Update "Get Involved" anchor link in README

- CodeGenerator.cpp
- CodeGeneratorTypes.h
- tests/p0960Test.cpp
- tests/p0960Test.expect
> Added support for P0960: Allow initializing aggregates from a parenthesized list of values

- Readme.md
I have tested in ArchLinux and NixOS and work fine.
> Add neovim plugin
